# Site settings
title: Darshan Santani
email: darshan.santani@gmail.com
author: Darshan Santani
alias: dsantani
description: "Homepage of Darshan Santani"
baseurl: "https://dsantani.github.io"
url: ""

# Google Analytics
ga_tracking_id: UA-777637-2

# Build settings
markdown: kramdown
permalink: pretty
